trigger:
- master
  
pool:
  vmImage: 'windows-latest'

variables:
- group: 'Library Common Vars'
    
steps:
  - task: PowerShell@2
    inputs:
      filePath: 'build.ps1'
      arguments: '-Target PushToNuget'
      pwsh: true
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)