trigger:
- master
  
pool:
  vmImage: 'windows-latest'

variables:
- group: 'Library Common Vars'
    
steps:
  - task: Cake@0
  inputs:
    script: 'build.cake'
    target: 'PushToNuget'
    verbosity: 'Verbose'